

CREATE TABLE test_artist_data (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(2000)
);

INSERT INTO test_artist_data
    (name, description )
    VALUES
        ('Fabian Egger', 'At the young age of 14, Fabian Egger is quickly establishing himself as one of the youngest flute virtuosos of his time. Fabian began to play the flute at the age of five under the tutelage of his parents who are both flutist. He later went on to study at the Pre-College of the Mozarteum Salzburg with Britta Bauer and in 2020 was admitted at the Hochschule für Musik und Tanz München, under grounds of artistic merit, as the youngest student ever admitted into the studio of world renowned flutists Prof. Andrea Lieberknecht. Fabian is a prize winner in several international competitions including the German Flute Society’s competition, International Concorso Zampetti, La Côte Flûte Festival Junior Competition and the Severino Gazzelloni Competition, to name a few. In 2021, Fabian was awarded First Prize in the Tampere Flute Fest Young Artist Competition Category B. He has appeared as a soloist with several orchestras included the Salzburg Chamber Soloists, Mitteldeutsches Kammerorchester, Philharmonie Bad Reichenhall and Orchestre de Chambre de Genève. Fabian also enjoys composing. Some of his recordings have been broadcasted on Germany’s BR Radio.'),
        ('Sebastian Jacot', 'Sébastian Jacot is currently working as Principal Flutist of the Gewandhaus Orchestra. A unique artist of his genre, Jacot has been described as “a flute rock star”, after affirming himself as one of the most brilliant flutists of his generation for winning first prizes in the most regarded flute competitions in the world including the Kobe International Flute Competition in 2013, the Carl Nielsen International Flute Competition in 2014, and the ARD Music Competition in 2015. Jacot has performed as a soloist with the Bayerische Rundfunk Symphony Orchestra, Munich Chamber Orchestra, Georgian Chamber Orchestra Ingolstadt, Orchestre de Chambre de Genève, Kansai Philharmonic Orchestra, Thai Philharmonic Orchestra, Kobe City Chamber Orchestra, Deutsche Staatsphilharmonie Mannheim, Gstaad Menuhin Academy Orchestra, and Osnabruck Theater Orchestra. He has also worked as Principal Flutists with the Budapest Festival Orchestra and the Berliner Philharmonic. A significant part of his life is dedicated to teaching. In 2020, he took a teaching position at the University of the Arts Bremen. Jacot plays a rare wooden Haynes from 1999 and a 14k Parmenon.'),
        ('Jenny Villanen', 'Jenny Villanen has held the Solo Piccolo position in the Helsinki Philharmonic Orchestra since 2007. Prior to that she held a position in the Guards Band of Finland. In addition to her permanent roles, Villanen has been in demand as a deputy in orchestras across Finland, including at the Finnish National Opera & Ballet, the Finnish Radio Symphony Orchestra, the Turku Philharmonic Orchestra, the Tampere Philharmonic Orchestra, the Savonlinna Opera Festival Orchestra, Tapiola Sinfonietta and Kymi Sinfonietta. Villanen has premiered numerous works by Finnish composers as both a soloist and chamber musician. She also enjoys playing a diverse range of music, especially with her Duo 2Clazz! and Quartet 4Clazz!.');